version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: kova
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - kova:/var/lib/postgresql/data
volumes:
  kova:
